### ISSUE TITLE
 Deprecated warning

### ISSUE THREAD

**Issue by madflow** [ztoben/assets-webpack-plugin#276]
Hello!

I am evaluation all of the different assets plugins (webpack-manifest-plugin, webpack-assets-manifest, assets-webpack-plugin so far).

This one yields a deprecation message on npm:

https://www.npmjs.com/package/assets-webpack-plugin

So is it? A lot of commits recently for a deprecated packge ;).

**Comment by ztoben** [comment]
I accidentally release a main release that was intended to be an alpha release, so I deprecated just that one version. So since the most recent non alpha or beta version is deprecated it gives that warning. I don't think it would give the deprecated warning when installing unless you were specifically using version `6.0.0`.

So in short, no it isn't deprecated and I'm working on supporting webpack 5 and will hopefully have a release out for it soon. :)
